services:
  mq:
    container_name: mq
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/passwords:/mosquitto/config/passwords:ro
    networks:
      - mqtt_internal

networks:
  mqtt_internal:
    internal: true
