global:
  scrape_interval: 5s

scrape_configs:
  - job_name: self_gaming_exporter
    static_configs:
      - targets: ["metrics_exporter:9108"]
  - job_name: node_exporter
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: dcgm_exporter
    static_configs:
      - targets: ["dcgm_exporter:9400"]
